//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""BallCatchInputs"",
            ""id"": ""38414730-4de8-470f-ad04-17919734facb"",
            ""actions"": [
                {
                    ""name"": ""Touch"",
                    ""type"": ""Value"",
                    ""id"": ""0a18d6e2-2eb5-4325-a1af-4aaf181e4ec8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""291df7b1-7a55-41e7-90d1-6a76ec46d6b9"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left Mouse Click"",
                    ""id"": ""eb7f344e-d5c8-4515-a3f4-9edcc0ee3c20"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""26d91083-aacf-4475-8956-b6a38a34530e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""3b391119-3355-4e42-9a74-49bf5f73f0ea"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BallCatchInputs
        m_BallCatchInputs = asset.FindActionMap("BallCatchInputs", throwIfNotFound: true);
        m_BallCatchInputs_Touch = m_BallCatchInputs.FindAction("Touch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BallCatchInputs
    private readonly InputActionMap m_BallCatchInputs;
    private List<IBallCatchInputsActions> m_BallCatchInputsActionsCallbackInterfaces = new List<IBallCatchInputsActions>();
    private readonly InputAction m_BallCatchInputs_Touch;
    public struct BallCatchInputsActions
    {
        private @PlayerInput m_Wrapper;
        public BallCatchInputsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch => m_Wrapper.m_BallCatchInputs_Touch;
        public InputActionMap Get() { return m_Wrapper.m_BallCatchInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BallCatchInputsActions set) { return set.Get(); }
        public void AddCallbacks(IBallCatchInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_BallCatchInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BallCatchInputsActionsCallbackInterfaces.Add(instance);
            @Touch.started += instance.OnTouch;
            @Touch.performed += instance.OnTouch;
            @Touch.canceled += instance.OnTouch;
        }

        private void UnregisterCallbacks(IBallCatchInputsActions instance)
        {
            @Touch.started -= instance.OnTouch;
            @Touch.performed -= instance.OnTouch;
            @Touch.canceled -= instance.OnTouch;
        }

        public void RemoveCallbacks(IBallCatchInputsActions instance)
        {
            if (m_Wrapper.m_BallCatchInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBallCatchInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_BallCatchInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BallCatchInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BallCatchInputsActions @BallCatchInputs => new BallCatchInputsActions(this);
    public interface IBallCatchInputsActions
    {
        void OnTouch(InputAction.CallbackContext context);
    }
}
